name: tests

on:
  push:
    branches-ignore:
    - '!master'
    path-ignore:
    - 'docs/**'


jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
    - name: Start Selenoid Server
      uses: Xotabu4/selenoid-github-action@v1
    - uses: actions/checkout@v1
    - name: Run tests
      env:
        SELENIUM_HUB_HOST: 'localhost'
      run: gradle test -Ptask=full_regression task -i
    - name: Create report


