name: tests

on:
  push:
    branches-ignore:
    - '!master'
    path-ignore:
    - 'docs/**'


jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
    - name: Start Selenoid Server